on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '42 8 * * *' # every day at 4:05am
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data from the API endpoint
      run: |-
        curl -s "https://www.dexerto.com/_next/data/J8_xJtDL4KzdXQn3woaIC/gaming.json" | jq '.pageProps.vertical.featuredPosts' > return.json
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
